- name: Install System Packages
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge {{ item.name }}' creates={{ item.creates }}
  with_items:
    - name: eix
      creates: /mnt/gentoo/usr/bin/eix
    - name: syslog-ng
      creates: /mnt/gentoo/usr/sbin/syslog-ng
    - name: cronie
      creates: /mnt/gentoo/etc/init.d/cronie
    - name: grub
      creates: /mnt/gentoo/usr/sbin/grub2-install

- name: Add syslog-ng to Default Run Configuration
  command: chroot /mnt/gentoo bash -c 'rc-update add syslog-ng default'

- name: Add cronie to Default Run Configuration
  command: chroot /mnt/gentoo bash -c 'rc-update add cronie default'

- name: Remount /dev to get /dev/mapper visible
  command: mount --rbind /dev /mnt/gentoo/dev

- name: Configure grub Defaults
  copy: src=grub_default dest=/mnt/gentoo/etc/default/grub mode=0644 owner=root group=root

- name: Install Grub to Boot Drive
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; grub2-install /dev/sda'

- name: Configure Grub Make Config
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; grub2-mkconfig -o /boot/grub/grub.cfg'

- name: Set Root Password
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; echo "root:{{ root_passwd }}" | /usr/sbin/chpasswd'


